<a href="https://colab.research.google.com/github/Gowtham492002/eye-cancer-patient/blob/main/SVM_in_EyeCancer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
data = pd.read_excel("eye cancer patient data sets.xlsx")

In [ ]:
data

,Patient Id,Age,Gender,Air Pollution,Alcohol use,Dust Allergy,OccuPational Hazards,Genetic Risk,chronic Lung Disease,Balanced Diet,...,Fatigue,Weight Loss,Shortness of Breath,Wheezing,Swallowing Difficulty,Clubbing of Finger Nails,Frequent Cold,Dry Cough,Snoring,Level
0,P1,33,1,2,4,5,4,3,2,2,...,3,4,2,2,3,1,2,3,4,Low
1,P10,17,1,3,1,5,3,4,2,2,...,1,3,7,8,6,2,1,7,2,Medium
2,P100,35,1,4,5,6,5,5,4,6,...,8,7,9,2,1,4,6,7,2,High
3,P1000,37,1,7,7,7,7,6,7,7,...,4,2,3,1,4,5,6,7,5,High
4,P101,46,1,6,8,7,7,7,6,7,...,3,2,4,1,4,2,4,2,3,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,P995,44,1,6,7,7,7,7,6,7,...,5,3,2,7,8,2,4,5,3,High
996,P996,37,2,6,8,7,7,7,6,7,...,9,6,5,7,2,4,3,1,4,High
997,P997,25,2,4,5,6,5,5,4,6,...,8,7,9,2,1,4,6,7,2,High
998,P998,18,2,6,8,7,7,7,6,7,...,3,2,4,1,4,2,4,2,3,High
999,P999,47,1,6,5,6,5,5,4,6,...,8,7,9,2,1,4,6,7,2,High

In [ ]:
data.isnull()

,Patient Id,Age,Gender,Air Pollution,Alcohol use,Dust Allergy,OccuPational Hazards,Genetic Risk,chronic Lung Disease,Balanced Diet,...,Fatigue,Weight Loss,Shortness of Breath,Wheezing,Swallowing Difficulty,Clubbing of Finger Nails,Frequent Cold,Dry Cough,Snoring,Level
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
data.isnull().sum()

Patient Id                  0
Age                         0
Gender                      0
Air Pollution               0
Alcohol use                 0
Dust Allergy                0
OccuPational Hazards        0
Genetic Risk                0
chronic Lung Disease        0
Balanced Diet               0
Obesity                     0
Smoking                     0
Passive Smoker              0
Chest Pain                  0
Coughing of Blood           0
Fatigue                     0
Weight Loss                 0
Shortness of Breath         0
Wheezing                    0
Swallowing Difficulty       0
Clubbing of Finger Nails    0
Frequent Cold               0
Dry Cough                   0
Snoring                     0
Level                       0
dtype: int64

In [ ]:
data.drop('Patient Id',axis=1,inplace=True)

In [ ]:
data

,Age,Gender,Air Pollution,Alcohol use,Dust Allergy,OccuPational Hazards,Genetic Risk,chronic Lung Disease,Balanced Diet,Obesity,...,Fatigue,Weight Loss,Shortness of Breath,Wheezing,Swallowing Difficulty,Clubbing of Finger Nails,Frequent Cold,Dry Cough,Snoring,Level
0,33,1,2,4,5,4,3,2,2,4,...,3,4,2,2,3,1,2,3,4,Low
1,17,1,3,1,5,3,4,2,2,2,...,1,3,7,8,6,2,1,7,2,Medium
2,35,1,4,5,6,5,5,4,6,7,...,8,7,9,2,1,4,6,7,2,High
3,37,1,7,7,7,7,6,7,7,7,...,4,2,3,1,4,5,6,7,5,High
4,46,1,6,8,7,7,7,6,7,7,...,3,2,4,1,4,2,4,2,3,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,44,1,6,7,7,7,7,6,7,7,...,5,3,2,7,8,2,4,5,3,High
996,37,2,6,8,7,7,7,6,7,7,...,9,6,5,7,2,4,3,1,4,High
997,25,2,4,5,6,5,5,4,6,7,...,8,7,9,2,1,4,6,7,2,High
998,18,2,6,8,7,7,7,6,7,7,...,3,2,4,1,4,2,4,2,3,High
999,47,1,6,5,6,5,5,4,6,7,...,8,7,9,2,1,4,6,7,2,High

In [ ]:
data.describe()

,Age,Gender,Air Pollution,Alcohol use,Dust Allergy,OccuPational Hazards,Genetic Risk,chronic Lung Disease,Balanced Diet,Obesity,...,Coughing of Blood,Fatigue,Weight Loss,Shortness of Breath,Wheezing,Swallowing Difficulty,Clubbing of Finger Nails,Frequent Cold,Dry Cough,Snoring
count,1000.000000,1000.000000,1000.0000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,...,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,37.174000,1.402000,3.8400,4.563000,5.165000,4.840000,4.580000,4.380000,4.491000,4.465000,...,4.859000,3.856000,3.855000,4.240000,3.777000,3.746000,3.923000,3.536000,3.853000,2.926000
std,12.005493,0.490547,2.0304,2.620477,1.980833,2.107805,2.126999,1.848518,2.135528,2.124921,...,2.427965,2.244616,2.206546,2.285087,2.041921,2.270383,2.388048,1.832502,2.039007,1.474686
min,14.000000,1.000000,1.0000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,27.750000,1.000000,2.0000,2.000000,4.000000,3.000000,2.000000,3.000000,2.000000,3.000000,...,3.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000
50%,36.000000,1.000000,3.0000,5.000000,6.000000,5.000000,5.000000,4.000000,4.000000,4.000000,...,4.000000,3.000000,3.000000,4.000000,4.000000,4.000000,4.000000,3.000000,4.000000,3.000000
75%,45.000000,2.000000,6.0000,7.000000,7.000000,7.000000,7.000000,6.000000,7.000000,7.000000,...,7.000000,5.000000,6.000000,6.000000,5.000000,5.000000,5.000000,5.000000,6.000000,4.000000
max,73.000000,2.000000,8.0000,8.000000,8.000000,8.000000,7.000000,7.000000,7.000000,7.000000,...,9.000000,9.000000,8.000000,9.000000,8.000000,8.000000,9.000000,7.000000,7.000000,7.000000

In [ ]:
X=data.drop('Level',axis=1)
X

,Age,Gender,Air Pollution,Alcohol use,Dust Allergy,OccuPational Hazards,Genetic Risk,chronic Lung Disease,Balanced Diet,Obesity,...,Coughing of Blood,Fatigue,Weight Loss,Shortness of Breath,Wheezing,Swallowing Difficulty,Clubbing of Finger Nails,Frequent Cold,Dry Cough,Snoring
0,33,1,2,4,5,4,3,2,2,4,...,4,3,4,2,2,3,1,2,3,4
1,17,1,3,1,5,3,4,2,2,2,...,3,1,3,7,8,6,2,1,7,2
2,35,1,4,5,6,5,5,4,6,7,...,8,8,7,9,2,1,4,6,7,2
3,37,1,7,7,7,7,6,7,7,7,...,8,4,2,3,1,4,5,6,7,5
4,46,1,6,8,7,7,7,6,7,7,...,9,3,2,4,1,4,2,4,2,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,44,1,6,7,7,7,7,6,7,7,...,7,5,3,2,7,8,2,4,5,3
996,37,2,6,8,7,7,7,6,7,7,...,7,9,6,5,7,2,4,3,1,4
997,25,2,4,5,6,5,5,4,6,7,...,8,8,7,9,2,1,4,6,7,2
998,18,2,6,8,7,7,7,6,7,7,...,9,3,2,4,1,4,2,4,2,3
999,47,1,6,5,6,5,5,4,6,7,...,8,8,7,9,2,1,4,6,7,2

In [ ]:
y=data.Level
y

0         Low
1      Medium
2        High
3        High
4        High
        ...
995      High
996      High
997      High
998      High
999      High
Name: Level, Length: 1000, dtype: object

In [ ]:
data.Level.value_counts()

High      365
Medium    332
Low       303
Name: Level, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [ ]:
X_train

,Age,Gender,Air Pollution,Alcohol use,Dust Allergy,OccuPational Hazards,Genetic Risk,chronic Lung Disease,Balanced Diet,Obesity,...,Coughing of Blood,Fatigue,Weight Loss,Shortness of Breath,Wheezing,Swallowing Difficulty,Clubbing of Finger Nails,Frequent Cold,Dry Cough,Snoring
687,53,2,4,5,6,5,5,4,6,7,...,8,8,7,9,2,1,4,6,7,2
500,52,1,3,2,1,2,3,5,1,2,...,1,1,1,1,3,2,3,2,3,3
332,18,2,6,8,7,7,7,6,7,7,...,9,3,2,4,1,4,2,4,2,3
979,53,1,3,1,4,2,3,2,3,3,...,2,2,2,3,4,1,5,2,6,2
817,27,1,3,1,4,3,2,3,4,3,...,1,3,2,2,4,2,2,3,4,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
835,44,1,2,3,2,1,3,2,1,2,...,2,2,2,3,2,1,2,3,2,3
192,52,1,6,8,7,7,7,6,2,4,...,3,2,7,6,5,1,9,3,4,2
629,22,1,6,8,7,7,7,6,2,4,...,3,2,7,6,5,1,9,3,4,2
559,37,1,7,7,7,7,6,7,7,7,...,8,4,2,3,1,4,5,6,7,5
684,36,1,6,7,7,7,7,7,6,7,...,7,8,5,7,6,7,8,7,6,2

In [ ]:
from sklearn.svm import SVC
classifier = SVC(kernel='linear', random_state=0)  
classifier.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

In [ ]:
from sklearn.metrics import confusion_matrix
y_pred= classifier.predict(X_test)

In [ ]:
y_pred

array(['High', 'Medium', 'Medium', 'High', 'Low', 'Medium', 'Medium',
       'Medium', 'Medium', 'Low', 'Low', 'High', 'Low', 'High', 'High',
       'Low', 'High', 'Medium', 'Low', 'Medium', 'High', 'Low', 'High',
       'High', 'High', 'High', 'Low', 'High', 'High', 'Medium', 'High',
       'Low', 'Low', 'High', 'Medium', 'Medium', 'Medium', 'Low', 'High',
       'Low', 'Medium', 'High', 'Medium', 'Medium', 'Medium', 'Low',
       'Low', 'High', 'High', 'Medium', 'High', 'Medium', 'Low', 'High',
       'Medium', 'Medium', 'Low', 'Low', 'High', 'High', 'Low', 'High',
       'High', 'High', 'Medium', 'Medium', 'Low', 'High', 'High', 'High',
       'Medium', 'Medium', 'Medium', 'Medium', 'Low', 'Low', 'Low',
       'Medium', 'Medium', 'High', 'Low', 'Medium', 'Low', 'High', 'High',
       'Medium', 'Low', 'Medium', 'Low', 'High', 'Medium', 'Low', 'High',
       'Low', 'Medium', 'Low', 'Medium', 'High', 'Low', 'High', 'Medium',
       'High', 'Medium', 'Low', 'High', 'Medium', 'High', 'Medium',
       'Medium', 'High', 'High', 'High', 'High', 'Medium', 'Low', 'Low',
       'Medium', 'Low', 'Low', 'Medium', 'High', 'Medium', 'High', 'Low',
       'Low', 'Medium', 'Low', 'Low', 'Low', 'Low', 'Low', 'Medium',
       'Low', 'Low', 'High', 'Medium', 'Low', 'Medium', 'Medium', 'High',
       'Medium', 'Low', 'Medium', 'Medium', 'Low', 'High', 'Low', 'Low',
       'Low', 'Low', 'Low', 'High', 'Medium', 'High', 'High', 'High',
       'Low', 'Medium', 'Medium', 'Low', 'Medium', 'High', 'High', 'High',
       'Low', 'Low', 'High', 'Low', 'High', 'Medium', 'High', 'High',
       'Low', 'Low', 'Low', 'Medium', 'High', 'High', 'High', 'Low',
       'High', 'High', 'High', 'High', 'High', 'Low', 'Low', 'Low',
       'High', 'High', 'High', 'Low', 'High', 'High', 'High', 'Medium',
       'Low', 'High', 'High', 'Low'], dtype=object)

In [ ]:
y_pred.shape

(200,)

In [ ]:
print("Accuracy of SVM Linear Classifier : ", classifier.score(X_test, y_test))

Accuracy of SVM Linear Classifier :  1.0

In [ ]:
confusion_matrix(y_test, y_pred)

array([[75,  0,  0],
       [ 0, 67,  0],
       [ 0,  0, 58]])